library(shiny)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readxl)
library(readr)
library(plotly)
library(lubridate)
library(shinycssloaders)
library(shinythemes)

addResourcePath("images", "images")

ui <- fluidPage(theme = shinytheme("cerulean"),
                
   includeCSS("css/styles.css"),
   
   titlePanel("Energy Usage Viewer"),
   
   sidebarLayout(
      sidebarPanel(
         a(href = "https://oaiti.org", target = "_blank", img(src = "images/oaiti_transparent.png", width = "135")),
         
         h4("About"),
         HTML("This app allows the uploading of energy data in particular formats and performs an analysis of that data. Each tab describes the format of the expected data. To see sample data in the proper format, please check out the Data folder on our <a href='https://github.com/OAITI/energy-usage/tree/master/data' target='_blank'>GitHub</a>"),
         
         hr(),
         
         conditionalPanel(condition = "input.tabs1 == 'Electricity'",
                          h4("Electricity Configuration"),
                          HTML("The expected format is an Excel spreadsheet with columns <b>Date</b>, <b>Start Time</b>, <b>Value</b>, and <b>Year</b>. Once the data has been uploaded, the results will be computed and displayed automatically. The date range can be selected to subset the time frame considered."),
                          hr(),
                          fileInput("elec", "Electricity Data", accept = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                          dateRangeInput("dates",
                                         "Electricity Date Range",
                                         start = "2016-01-01",
                                         end = "2017-10-30")
         ),
         conditionalPanel(condition = "input.tabs1 == 'Gas'",
                          h4("Gas Configuration"),
                          HTML("The expected format is an Excel spreadsheet generated by <b>Portfolio Manager</b> with a sheet called <b>Meter Entries</b>."),
                          hr(),
                          fileInput("gas", "Gas Data", accept = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                          dateRangeInput("gas_dates",
                                         "Gas Date Range",
                                         start = "2013-01-01",
                                         end = "2017-10-30")
         ),
         conditionalPanel(condition = "input.tabs1 == 'Temperature'",
                          h4("Temperature Configuration"),
                          HTML("The expected format is a CSV file with columns <b>Bill month</b>, <b>Therms used</b>, and <b>Average daily temperature</b>. This uses the hourly <b>Electricity</b> data uploaded in the first tab."),
                          hr(),
                          fileInput("temp", "Temperature Data", accept = "text/csv"),
                          dateRangeInput("temperature_dates",
                                         "Temperature Date Range",
                                         start = "2016-01-01",
                                         end = "2017-10-01")
         ),
         
         hr(),
         
         helpText("© Copyright 2017 Omni Analytics Innovative Technologies Initiative")
      ),
      
      mainPanel(
          tabsetPanel(id = "tabs1",
              tabPanel("Electricity",
                       h4("Electricity Usage Over Time"),
                       selectInput("aggregation", "Aggregation Level", choices = c("Daily", "Weekly", "Monthly", "Yearly"), selected = "Monthly"),
                       withSpinner(plotlyOutput("time_series")),
                       hr(),
                       h4("Hourly Electricity Usage"),
                       selectInput("facet", "Grouping", choices = c("None", "Week Day" = "WeekDay", "Month")),
                       withSpinner(plotlyOutput("hourly_plot", height = "600px"))
              ),
              tabPanel("Gas",
                       h4("Gas Usage Over Time"),
                       selectInput("gas_aggregation", "Aggregation Level", choices = c("Monthly", "Yearly"), selected = "Monthly"),
                       withSpinner(plotlyOutput("gas_time_series"))
              ),
              tabPanel("Temperature",
                       h4("Electricity Usage by Temperature"),
                       withSpinner(plotlyOutput("elec_temp")),
                       hr(),
                       h4("Gas Usage by Temperature"),
                       withSpinner(plotlyOutput("gas_temp"))
              )
          )
      )
   )
)

server <- function(input, output, session) {
  
  observe({
    if (!is.null(elec_data())) {
      updateDateRangeInput(session, "dates", 
                           min = min(as.Date(elec_data()$Date)), 
                           max = max(as.Date(elec_data()$Date)), 
                           start = min(as.Date(elec_data()$Date)), 
                           end = max(as.Date(elec_data()$Date)))
    }
      
      if (!is.null(gas_series())) {
          updateDateRangeInput(session, "gas_dates", 
                               min = min(as.Date(gas_series()$`Start Date`)), 
                               max = max(as.Date(gas_series()$`End Date`)), 
                               start = min(as.Date(gas_series()$`Start Date`)), 
                               end = max(as.Date(gas_series()$`End Date`)))
      }
  }, suspended = TRUE)
   
   elec_data <- reactive({
     if (is.null(input$elec)) return(read_xlsx("data/elec_hourly.xlsx"))
     
     return(read_xlsx(input$elec$datapath))
   })
   
   elec_series <- reactive({
     if (is.null(elec_data())) return(NULL)
       
       myagg <- switch(input$aggregation, "Daily" = c("Day", "Month", "Year"), 
                       "Weekly" = c("Week", "Year"),
                       "Monthly" = c("Month", "Year"),
                       "Yearly" = "Year")
       
        elec_data() %>% 
            mutate(Date = as.Date(Date)) %>%
            filter(Date >= input$dates[1], Date <= input$dates[2]) %>%
            mutate(SDate = ymd(Date),
                   Day = yday(SDate),
                   Week = week(SDate),
                   Month = month(SDate, label = TRUE),
                   Year = year(SDate)) %>%
            mutate(Week = replace(Week, Week == 53, 52)) %>%
            group_by_at(vars(one_of(myagg))) %>%
            summarise(Usage = sum(Value),
                      Date = SDate[1]) %>%
            arrange(Date)
   })
   
   elec_monthly <- reactive({
       if (is.null(elec_data())) return(NULL)
       
       elec_data() %>% 
           mutate(Date = as.Date(Date)) %>%
           filter(Date >= input$temperature_dates[1], Date <= input$temperature_dates[2]) %>%
           mutate(SDate = ymd(Date),
                  Month = month(SDate, label = TRUE),
                  Year = year(SDate)) %>%
           group_by(Year, Month) %>%
           summarise(Usage = sum(Value)) %>%
           mutate(Date = ymd(paste(Year, Month, "01", sep = "-"))) %>%
           arrange(Date)
   })
   
   elec_hourly <- reactive({
       if (is.null(elec_data())) return(NULL)
           
       elec_data() %>%
           mutate(Date = as.Date(Date)) %>%
           filter(Date >= input$dates[1], Date <= input$dates[2]) %>%
           mutate(SDate = ymd(Date),
                  WeekDay = wday(SDate, label = TRUE),
                  Month = month(SDate, label = TRUE),
                  Hour = factor(paste0(`Start Time` / 100, ":00"), levels = paste0(0:23, ":00")),
                  Usage = Value)
   })
   
   output$time_series <- renderPlotly({
       if (is.null(elec_series())) return(NULL)
       
       mydat <- elec_series()
       
       if (input$aggregation == "Yearly") {
           mydat$Date <- ymd(paste(year(mydat$Date), "01", "01", sep = "-"))
           mytext <- paste("Usage:", round(mydat$Usage, digits = 2))
       } else if (input$aggregation == "Monthly") {
           mytext <- paste("Month:", format(as.Date(mydat$Date), "%b %y"),
                           "<br>Usage:", round(mydat$Usage, digits = 2))
       } else {
           mytext <- paste("Date:", as.Date(mydat$Date),
                           "<br>Usage:", round(mydat$Usage, digits = 2))
       }
       
       g <- ggplot(data = mydat, aes(x = Date, y = Usage, group = 1, 
                                     text = mytext)) +
           geom_line() +
           theme_bw() +
           theme(axis.text.x = element_text(angle = 45, size = 8))
       
       if (input$aggregation == "Yearly") {
           g <- g + scale_x_date(date_breaks = "1 year", date_minor_breaks = "1 month", date_labels = "%Y")
       } else {
           g <- g + scale_x_date(date_breaks = "1 month", date_labels = "%b %Y")
       }
       
       if (input$aggregation != "Daily") g <- g + geom_point()
       
       ggplotly(g, tooltip = c("text"))
   })
   
   elec_grouped <- reactive({
       if (is.null(elec_data())) return(NULL)
       
       myfunc <- get(input$facet)
   })
   
   output$hourly_plot <- renderPlotly({
     if (is.null(elec_hourly())) return(NULL)
       
       hourly_elec_data <- elec_hourly() %>%
           mutate(Outlier = Usage >= quantile(Usage, .75) + 1.5 * IQR(Usage) | 
                      Usage <= quantile(Usage, .25) - 1.5 * IQR(Usage))
           
     g <- ggplot(data = hourly_elec_data, aes(x = Hour, y = Usage, text = SDate)) +
         geom_boxplot() +
         geom_point(data = filter(hourly_elec_data, Outlier)) +
         theme_bw() +
         theme(axis.text.x = element_text(angle = 45, size = 6))
     
     if (input$facet != "None") g <- g + facet_wrap(as.formula(paste("~", input$facet)), scales = "free_x")
     
     ggplotly(g)
   })
   
   gas_data <- reactive({
       if (is.null(input$gas)) return(read_xlsx("data/gas_data.xlsx", sheet = "Meter Entries", skip = 5))
       
       return(read_xlsx(input$gas$datapath, sheet = "Meter Entries", skip = 5))
   })
   
   gas_series <- reactive({
       if (is.null(gas_data())) return(NULL)
       
       all_agg <- gas_data() %>%
           select(`Meter Type`, `Start Date`, `End Date`, `Usage/Quantity`, `Usage Units`, `Cost ($)`) %>%
           mutate(SDate=as.Date(`Start Date`), EDate=as.Date(`End Date`), Diff_Days=EDate-SDate) %>%
           filter(SDate >= input$gas_dates[1], EDate <= input$gas_dates[2])
       
       myagg <- switch(input$gas_aggregation,
                       "Monthly" = c("Meter Type", "Month", "Year"),
                       "Yearly" = c("Meter Type", "Year"))
       
       all_agg %>% # Take the agg data
           mutate(Cost = replace(`Cost ($)`, `Cost ($)` == "Not Available", NA)) %>% # Set the not available costs to NA
           rowwise() %>% # Process each row (no grouping)
           do(date_seq = seq(.$SDate, .$EDate, by = "1 day"), # Create column where each element is every day of the billing period
              `Meter Type` = .$`Meter Type`[1], # Store meter type
              Usage = .$`Usage/Quantity`[1], # Store Usage
              Cost = .$Cost[1]) %>% # Store cost
           mutate(`Meter Type` = unlist(`Meter Type`), # Convert back from a list
                  Usage = Usage / length(date_seq), # Divide usage by the number of days in the billing period
                  Cost = as.numeric(Cost) / length(date_seq)) %>% # Divide cost by the number of days in the billing period
           unnest() %>% # Unnest the data frame (this expands it to one row per every day in date_seq)
           mutate(Year = year(date_seq), Month = month(date_seq)) %>%
           group_by_at(vars(one_of(myagg))) %>%
           summarise(Usage = sum(Usage), Cost = sum(Cost)) %>% # Sum up the per day usage to count the amount for each month
           mutate(Date = ymd(paste(Year, ifelse(input$gas_aggregation == "Monthly", Month, "01"), "01", sep = "-"))) %>% # Create a date column (assuming first of the month)
           filter(`Meter Type` == "Natural Gas")
   })
   
   output$gas_time_series <- renderPlotly({
       if (is.null(gas_series())) return(NULL)
       
       g <- ggplot(data = gas_series(), aes(x = Date, y = Usage, group = 1,
                                            text = paste("Usage:", round(Usage, digits = 2)))) +
           geom_point() +
           geom_line() +
           theme_bw() +
           theme(axis.text.x = element_text(angle = 45, size = 8))
       
       if (input$gas_aggregation == "Yearly") {
           g <- g + scale_x_date(date_breaks = "1 year", date_minor_breaks = "1 month", date_labels = "%Y")
       } else {
           g <- g + scale_x_date(date_breaks = "3 months", date_minor_breaks = "1 month", date_labels = "%b %Y")
       }
       
       ggplotly(g, tooltip = c("text"))
   })
   
   temperature_data <- reactive({
       if (is.null(input$temp)) {
           temperature_data <- read_csv("data/temperature_data.csv")
       } else {
           temperature_data <- read_csv(input$temp$datapath)
       }

       return(temperature_data %>%
                  mutate(Date = mdy(`Bill month`)) %>%
                  filter(Date >= input$temperature_dates[1], Date <= input$temperature_dates[2]) %>%
                  left_join(elec_monthly(), by = c("Date" = "Date")) %>%
                  rename(`kWh Used` = Usage) %>%
                  slice(-1))
   })
   
   output$elec_temp <- renderPlotly({
       if (is.null(temperature_data())) return(NULL)
       
       ggplotly(ggplot(data = temperature_data(), aes(x = `Average daily temperature`, y = `kWh Used`, text = paste("Month:", format(Date, "%b %Y")))) +
                    geom_point() +
                    theme_bw())
   })
   
   output$gas_temp <- renderPlotly({
       if (is.null(temperature_data())) return(NULL)
       
       ggplotly(ggplot(data = temperature_data(), aes(x = `Average daily temperature`, y = `Therms used`, text = paste("Month:", format(Date, "%b %Y")))) +
                    geom_point() +
                    theme_bw())
   })
}

shinyApp(ui = ui, server = server)
